### ISSUE TITLE
Maximum call size problem with render

### ISSUE THREAD

**Issue by cmarrero01** [cheeriojs/dom-serializer#73]
I had a bit problem parsing some html content:

```
RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at Object.encodeXML (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/entities/lib/encode.js:58:6)
    at renderText (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:136:21)
    at module.exports (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:91:17)
    at renderTag (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:116:14)
    at module.exports (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:83:17)
    at renderTag (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:116:14)
    at module.exports (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:83:17)
    at renderTag (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:116:14)
    at module.exports (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:83:17)
    at renderTag (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:116:14)
    at module.exports (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:83:17)
    at renderTag (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:116:14)
    at module.exports (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:83:17)
    at renderTag (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:116:14)
    at module.exports (/home/ubuntu/crawler/crawler/node_modules/cheerio/node_modules/dom-serializer/index.js:83:17)

```

I think, the problem is this for:

```

var render = module.exports = function(dom, opts) {
  if (!Array.isArray(dom) && !dom.cheerio) dom = [dom];
  opts = opts || {};

  var output = '';

  for(var i = 0; i < dom.length; i++){
    var elem = dom[i];

    if (elem.type === 'root')
      output += render(elem.children, opts);
    else if (ElementType.isTag(elem))
      output += renderTag(elem, opts);
    else if (elem.type === ElementType.Directive)
      output += renderDirective(elem);
    else if (elem.type === ElementType.Comment)
      output += renderComment(elem);
    else if (elem.type === ElementType.CDATA)
      output += renderCdata(elem);
    else
      output += renderText(elem, opts);
  }

  return output;
};
```

This need to be async for my opinion, but how to make this async without break the librerias like cheerio that use this library?

**Comment by fb55** [comment]
The solution would be to switch to an iterative algorithm (instead of recursive). For now, we simply don't support deeply nested documents.
